{% set name = "opensesame" %}
{% set pypiname = "python-" + name %}
{% set version = "3.3.0a70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz"
  sha256: "dc42326a5a62aa1bd36bd54c5e51396975b3f295d0e7fe678229ea85b0bed0ff"

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  host:
    - pyyaml
    - pip
    - python

  run:
    - python
    - pyqt
    - qdatamatrix >=0.1.21
    - pseudorandom
    - fileinspector
    - qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core
    - pyqode.python

test:
  imports:
    - libopensesame
    - libqtopensesame

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'

about:
  home: https://github.com/smathot/OpenSesame
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Graphical experiment builder for the social sciences'
  dev_url: https://github.com/smathot/OpenSesame
  doc_url: http://osdoc.cogsci.nl

extra:
  recipe-maintainers:
    - dschreij
    - smathot
