{% set name = "opensesame" %}
{% set pypiname = "python-" + name %}
{% set version = "3.3.0a67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz"
  sha256: "b659709474639e8bb5d4074be3e3b56446dfb3392a2c140aa702a9e637071b2b"

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]

  host:
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - xorg-libxfixes  # [linux]
    - pyyaml
    - pip
    - python

  run:
    - python
    - pyqt
    - qdatamatrix >=0.1.21
    - pseudorandom
    - fileinspector
    - qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core
    - pyqode.python

test:
  imports:
    - libopensesame
    - libqtopensesame

app:
  entry: opensesame
  icon: opensesame.png
  summary: 'Graphical experiment builder for the social sciences'

about:
  home: https://github.com/smathot/OpenSesame
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: 'Graphical experiment builder for the social sciences'

extra:
  recipe-maintainers:
    - dschreij
    - smathot
