{% set name = "opensesame" %}
{% set pypiname = "python-" + name %}
{% set version = "3.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 636af215ded9c68102135265a29b678877d1ea01ee7307ff449692649e649f46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - opensesame = libqtopensesame.__main__:opensesame
    - opensesamerun = libqtopensesame.__main__:opensesamerun

requirements:
  host:
    - pyyaml
    - pip
    - python

  run:
    - python
    - pyqt
    - qdatamatrix >=0.1.21
    - pseudorandom
    - fileinspector
    - qnotifications >=2.0.3
    - pyyaml
    - webcolors
    - pyserial
    - markdown
    - pyflakes
    - shapely
    - pillow
    - pyqode.core
    - pyqode.python

test:
  imports:
    - libopensesame
    - libqtopensesame

app:
  entry: opensesame
  icon: opensesame.png
  summary: Graphical experiment builder for the social sciences

about:
  home: https://github.com/smathot/OpenSesame
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Graphical experiment builder for the social sciences
  dev_url: https://github.com/smathot/OpenSesame
  doc_url: http://osdoc.cogsci.nl

extra:
  recipe-maintainers:
    - dschreij
    - smathot
